name: Luacheck

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  luacheck:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: extractions/setup-just@v2
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: lua5.3 liblua5.3-dev luarocks npm curl
          version: 2.0
      - name: Update PATH
        run: export PATH=$HOME/.luarocks/bin/:$PATH
      - name: Lint
        run: just lint
      - name: Build
        run: just build